### ISSUE TITLE
ls8tools

### ISSUE THREAD

**Issue by jaimebayes** [jorisvandenbossche/geopandas-tutorial#5]
Hi Joris, 

I found this syntaxerror in ls8tools.py file, how can I fix it? Thanks in advance, Jaime

Traceback (most recent call last):

  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-0394863741c9>", line 3, in <module>
    from utils import ls8tools

  File "C:\github\python_gdal_workshop\utils\ls8tools.py", line 141
    if 'win' in sys.platform:
    ^
SyntaxError: invalid character in identifier

**Comment by jorisvandenbossche** [comment]
Is it possible this is from a different tutorial? I am not aware of a `ls8tools.py` in here.

**Comment by jaimebayes** [comment]
Sorry Joris, my mistake.
